openapi: 3.0.1
info:
  title: naephi
  description: here to relief you from nifi activies.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /flow:
    post:
      operationId: initiateFlow
      tags:
        - flow
      summary: initiate a new processing flow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/flowRequest'
      responses:
        202:
          description: Accepted
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
security:
  - {}
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    flowRequest:
      oneOf:
        - $ref: '#/components/schemas/changesetFlowRequest'
      discriminator:
        propertyName: type
        mapping:
          changeset: '#/components/schemas/changesetFlowRequest'
    baseFlow:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          description: Identifies the specific flow logic to execute.
    changesetFlowRequest:
      allOf:
        - $ref: '#/components/schemas/baseFlow'
        - type: object
          required:
            - id
          properties:
            type:
              type: string
              enum: [changeset]
            id:
              type: string
              format: uuid
