{{- $releaseName := .Release.Name -}}
{{- $chartName := include "naephi.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "naephi.fullname" .) }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "naephi.environment" . }}
    release: {{ $releaseName }}
    {{- include "naephi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.redis }}
  {{- if or (ne .username "") (ne .password "") }}
  REDIS_USERNAME: {{ .username | b64enc }}
  REDIS_PASSWORD: {{ .password | b64enc }}
  {{- end }}
  REDIS_ENABLE_SSL_AUTH: {{ .enableSslAuth | toString | b64enc }}
  {{- if .enableSslAuth }}
  REDIS_CA_PATH: {{ .sslPaths.ca | b64enc }}
  REDIS_KEY_PATH: {{ .sslPaths.key | b64enc }}
  REDIS_CERT_PATH: {{ .sslPaths.cert | b64enc }}
  {{- end }}
  {{- end }}

  {{- with .Values.bullmq }}
  {{- if or (ne .username "") (ne .password "") }}
  BULLMQ_USERNAME: {{ .username | b64enc }}
  BULLMQ_PASSWORD: {{ .password | b64enc }}
  {{- end }}
  BULLMQ_ENABLE_SSL_AUTH: {{ .enableSslAuth | toString | b64enc }}
  {{- if .enableSslAuth }}
  BULLMQ_CA_PATH: {{ .sslPaths.ca | b64enc }}
  BULLMQ_KEY_PATH: {{ .sslPaths.key | b64enc }}
  BULLMQ_CERT_PATH: {{ .sslPaths.cert | b64enc }}
  {{- end }}
  {{- end }}

  {{- range $clientName, $clientConfig := .Values.env.app.clients }}
  {{- if $clientConfig.auth }}
  {{- $client := $clientName | snakecase | upper }}
  APP_CLIENTS_{{ $client }}_AUTH_TYPE: {{ $clientConfig.auth.type | b64enc }}
  {{- if eq $clientConfig.auth.type "basic" }}
  APP_CLIENTS_{{ $client }}_AUTH_USERNAME: {{ $clientConfig.auth.username | b64enc }}
  APP_CLIENTS_{{ $client }}_AUTH_PASSWORD: {{ $clientConfig.auth.password | b64enc }}
  {{- else if eq $clientConfig.auth.type "oauth2" }}
  APP_CLIENTS_{{ $client }}_AUTH_ACCESS_TOKEN: {{ $clientConfig.auth.accessToken | b64enc }}
  {{- else if eq $clientConfig.auth.type "oauth1" }}
  APP_CLIENTS_{{ $client }}_AUTH_ACCESS_TOKEN: {{ $clientConfig.auth.accessToken | b64enc }}
  APP_CLIENTS_{{ $client }}_AUTH_CONSUMER_KEY: {{ $clientConfig.auth.consumerKey | b64enc }}
  APP_CLIENTS_{{ $client }}_AUTH_CONSUMER_SECRET: {{ $clientConfig.auth.consumerSecret | b64enc }}
  APP_CLIENTS_{{ $client }}_AUTH_ACCESS_TOKEN_SECRET: {{ $clientConfig.auth.accessTokenSecret | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
