{{- $releaseName := .Release.Name -}}
{{- $chartName := include "naephi.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "naephi.fullname" .) }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "naephi.environment" . }}
    release: {{ $releaseName }}
    {{- include "naephi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.env.redis }}
  REDIS_USERNAME: {{ .username | b64enc }}
  REDIS_PASSWORD: {{ .password | b64enc }}
  REDIS_ENABLE_SSL_AUTH: {{ .enableSslAuth | toString | b64enc }}
  {{- if .enableSslAuth }}
  REDIS_CA_PATH: {{ .sslPaths.ca | b64enc }}
  REDIS_KEY_PATH: {{ .sslPaths.key | b64enc }}
  REDIS_CERT_PATH: {{ .sslPaths.cert | b64enc }}
  {{- end }}
  {{- end }}

  {{- with .Values.env.bullmq }}
  BULMQ_USERNAME: {{ .username | b64enc }}
  BULMQ_PASSWORD: {{ .password | b64enc }}
  BULMQ_ENABLE_SSL_AUTH: {{ .enableSslAuth | toString | b64enc }}
  {{- if .enableSslAuth }}
  BULMQ_CA_PATH: {{ .sslPaths.ca | b64enc }}
  BULMQ_KEY_PATH: {{ .sslPaths.key | b64enc }}
  BULMQ_CERT_PATH: {{ .sslPaths.cert | b64enc }}
  {{- end }}
  {{- end }}

  {{- $clientEnvMap := dict
    "osmApi"         "OSM_API"
    "osmSyncTracker" "OSM_SYNC_TRACKER"
    "changeMerger"   "CHANGE_MERGER"
    "idToOsm"        "ID_TO_OSM"
  }}
  {{- range $key, $envKey := $clientEnvMap }}
  {{- $c := index $.Values.env.app.clients $key }}
  {{- if $c.auth }}
  APP_CLIENTS_{{ $envKey }}_AUTH_TYPE: {{ $c.auth.type | b64enc }}
  {{- if eq $c.auth.type "basic" }}
  APP_CLIENTS_{{ $envKey }}_AUTH_USERNAME: {{ $c.auth.username | b64enc }}
  APP_CLIENTS_{{ $envKey }}_AUTH_PASSWORD: {{ $c.auth.password | b64enc }}
  {{- else if eq $c.auth.type "oauth2" }}
  APP_CLIENTS_{{ $envKey }}_AUTH_ACCESS_TOKEN: {{ $c.auth.accessToken | b64enc }}
  {{- else if eq $c.auth.type "oauth1" }}
  APP_CLIENTS_{{ $envKey }}_AUTH_ACCESS_TOKEN: {{ $c.auth.accessToken | b64enc }}
  APP_CLIENTS_{{ $envKey }}_AUTH_CONSUMER_KEY: {{ $c.auth.consumerKey | b64enc }}
  APP_CLIENTS_{{ $envKey }}_AUTH_CONSUMER_SECRET: {{ $c.auth.consumerSecret | b64enc }}
  APP_CLIENTS_{{ $envKey }}_AUTH_ACCESS_TOKEN_SECRET: {{ $c.auth.accessTokenSecret | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
