global:
  cloudProvider: {}
  tracing: {}
  metrics: {}

mclabels:
  component: backend
  partOf: boilerplates
  owner: common
  prometheus:
    enabled: true

enabled: true
replicaCount: 1
revisionHistoryLimit: 5
nodePort: 30030
resetOnConfigChange: false

nameOverride: ""
fullnameOverride: ""

configManagement:
  offlineMode: false
  name: 'service-name'
  version: 'latest'
  serverUrl: 'http://localhost:8080/api'

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []

sidecars: []

cloudProvider:
  dockerRegistryUrl: ''
  imagePullSecretName: ''
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: naephi
  pullPolicy: IfNotPresent

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  app:
    uiPath: /ui
    initTimeout: 30000
    osmIdResolver: tracker
    flows:
      changesetUpload:
        maxAttempts: 10
    queues:
      changesetPreUpload:
        job:
          attempts: 3
          delay: 0
          backoff:
            type: exponential
            delay: 1000
        worker:
          concurrency: 1
          limiter:
            enabled: false
            max: 100
            duration: 1000
          maxStalledCount: 1
          stalledInterval: 30000
          removeOnComplete:
            age: 3600
            count: 1000
          removeOnFail:
            age: 2419200
            # count: 100000
      changesetUpload:
        job:
          attempts: 3
          delay: 0
          backoffType: exponential
          backoffDelay: 1000
        worker:
          concurrency: 1
          limiter:
            enabled: false
            max: 100
            duration: 1000
          maxStalledCount: 1
          stalledInterval: 30000
          removeOnComplete:
            age: 3600
            count: 1000
          removeOnFail:
            age: 2419200
            # count: 100000
      changesetPostUpload:
        job:
          attempts: 3
          delay: 0
          backoffType: exponential
          backoffDelay: 1000
        worker:
          concurrency: 1
          limiter:
            enabled: false
            max: 100
            duration: 1000
          maxStalledCount: 1
          stalledInterval: 30000
          removeOnComplete:
            age: 3600
            count: 1000
          removeOnFail:
            age: 2419200
            # count: 100000
      changesetClosure:
        job:
          attempts: 3
          delay: 0
          backoffType: exponential
          backoffDelay: 1000
        worker:
          concurrency: 1
          limiter:
            enabled: false
            max: 100
            duration: 1000
          maxStalledCount: 1
          stalledInterval: 30000
          removeOnComplete:
            age: 3600
            count: 1000
          removeOnFail:
            age: 2419200
            # count: 100000
        batch:
          size: 10
          minSize: 1
          timeout: 5000
      changesetRedisCleanup:
        job:
          attempts: 3
          delay: 0
          backoffType: exponential
          backoffDelay: 1000
        worker:
          concurrency: 1
          limiter:
            enabled: false
            max: 100
            duration: 1000
          maxStalledCount: 1
          stalledInterval: 30000
          removeOnComplete:
            age: 3600
            count: 1000
          removeOnFail:
            age: 2419200
            # count: 100000
        batch:
          size: 10
          minSize: 1
          timeout: 5000
      changesetOsmCleanup:
        job:
          attempts: 3
          delay: 0
          backoffType: exponential
          backoffDelay: 1000
        worker:
          concurrency: 1
          limiter:
            enabled: false
            max: 100
            duration: 1000
          maxStalledCount: 1
          stalledInterval: 30000
          removeOnComplete:
            age: 3600
            count: 1000
          removeOnFail:
            age: 2419200
            # count: 100000
        batch:
          size: 10
          minSize: 1
          timeout: 5000
    clients:
      osmApi:
        url: http://localhost:3000
        timeout: 10000
        retryStrategy:
          enabled: false
          # retries: 3
          # shouldResetTimeout: false
          # isExponential: false
          # delay: 100
        headers: '{}'
        # auth:
        #   type: oauth2
        #   accessToken: ""
        #   type: basic
        #   username: ""
        #   password: ""
        #   type: oauth1
        #   accessToken: ""
        #   consumerKey: ""
        #   consumerSecret: ""
        #   accessTokenSecret: ""
      osmSyncTracker:
        url: http://localhost:3001
        timeout: 10000
        retryStrategy:
          enabled: false
          # retries: 3
          # shouldResetTimeout: false
          # isExponential: false
          # delay: 100
        headers: '{}'
      changeMerger:
        url: http://localhost:3002
        timeout: 10000
        retryStrategy:
          enabled: false
          # retries: 3
          # shouldResetTimeout: false
          # isExponential: false
          # delay: 100
        headers: '{}'
      idToOsm:
        url: http://localhost:3003
        timeout: 10000
        retryStrategy:
          enabled: false
          # retries: 3
          # shouldResetTimeout: false
          # isExponential: false
          # delay: 100
        headers: '{}'

  redis:
    host: localhost
    port: 6379
    username: ""
    password: ""
    db: 0
    # keyPrefix: "{ingestion}"
    enableSslAuth: false
    sslPaths:
      ca: ""
      key: ""
      cert: ""

  bullmq:
    host: localhost
    port: 6380
    username: ""
    password: ""
    db: 0
    keyPrefix: "{naephi}"
    enableSslAuth: false
    sslPaths:
      ca: ""
      key: ""
      cert: ""

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
  host: ''
  timeout:
    enabled: false  # defaults to 30s by openshift
    duration: 60s  # supported units (us, ms, s, m, h, d)
  rewriteTarget: ''
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    useCerts: false
    certificate: ''
    key: ''
    caCertificate: ''

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
